### ISSUE TITLE
Is there a plan to include Security Permissions on queue creation?

### ISSUE THREAD

**Issue by germansak** [dotnetdev-kr/Experimental.System.Messaging#3]
When you create a queue, its owner is the current user and access permissions are defined only to it. I'd like to know if there are plans to include MessageQueue.SetPermissions method.
Thanks and let me know if I can be of any help

**Comment by rkttu** [comment]
Thanks for your feedback. As I mentioned in the readme, this project is not a proper implementation. It just provides basic and limited features. If you can contribute to this project, you could help it. But instead of assist on this project, I recommend that you will be better to stay .NET Framework or move to other cross-platform message queue implementation such as NATS.

**Comment by csrowell** [comment]
@germansak Check out https://github.com/weloytty/MSMQ.Messaging
